-- ============================================================================
-- LISTING AUTOMATION -- complete, final, consolidated version.
-- Covers: the DATA_PRODUCT node (live from real listings) and the
-- SHARED_AS edges linking semantic views to the listings they belong to.
--
-- Run this file BEFORE the table-lineage file, since RELATIONSHIPS_VW
-- (in the other file) references LISTING_SEMANTIC_VIEW_MAP, created here.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- One-time prerequisite grants (safe to re-run even if already granted).
-- ----------------------------------------------------------------------------
USE ROLE ACCOUNTADMIN;
GRANT CREATE TABLE ON SCHEMA NEO4J_LINEAGE_DB.PUBLIC TO ROLE NEO4J_LINEAGE_ROLE;
GRANT CREATE TASK ON SCHEMA NEO4J_LINEAGE_DB.PUBLIC TO ROLE NEO4J_LINEAGE_ROLE;
GRANT CREATE PROCEDURE ON SCHEMA NEO4J_LINEAGE_DB.PUBLIC TO ROLE NEO4J_LINEAGE_ROLE;
GRANT CREATE VIEW ON SCHEMA NEO4J_LINEAGE_DB.PUBLIC TO ROLE NEO4J_LINEAGE_ROLE;

USE ROLE NEO4J_LINEAGE_ROLE;
USE WAREHOUSE NEO4J_LINEAGE_WH;
USE DATABASE NEO4J_LINEAGE_DB;
USE SCHEMA PUBLIC;

-- ----------------------------------------------------------------------------
-- Procedure: derives "which semantic view belongs to which listing" live,
-- via SHOW GRANTS TO SHARE for every real listing -- no hardcoding.
-- EXECUTE AS CALLER is required (without it: "current user not accessible
-- in stored procedure").
-- ----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE NEO4J_LINEAGE_DB.PUBLIC.REFRESH_LISTING_SEMANTIC_VIEW_MAP()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    v_listing_name VARCHAR;
    v_share_name VARCHAR;
    listings_cursor CURSOR FOR
        SELECT NAME, SHARE FROM TASTY_BYTES_DB.INFORMATION_SCHEMA.LISTINGS;
BEGIN
    CREATE OR REPLACE TABLE NEO4J_LINEAGE_DB.PUBLIC.LISTING_SEMANTIC_VIEW_MAP (
        SEMANTIC_VIEW_NAME VARCHAR,
        LISTING_NAME VARCHAR
    );

    FOR rec IN listings_cursor DO
        v_listing_name := rec.NAME;
        v_share_name := rec.SHARE;

        EXECUTE IMMEDIATE 'SHOW GRANTS TO SHARE ' || v_share_name;

        INSERT INTO NEO4J_LINEAGE_DB.PUBLIC.LISTING_SEMANTIC_VIEW_MAP (SEMANTIC_VIEW_NAME, LISTING_NAME)
        SELECT DISTINCT SPLIT_PART("name", '.', -1), :v_listing_name
        FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
        WHERE "granted_on" = 'SEMANTIC_VIEW';
    END FOR;

    RETURN 'Refreshed listing-semantic-view map at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;

-- Run it once now, and check the result.
CALL NEO4J_LINEAGE_DB.PUBLIC.REFRESH_LISTING_SEMANTIC_VIEW_MAP();
SELECT * FROM NEO4J_LINEAGE_DB.PUBLIC.LISTING_SEMANTIC_VIEW_MAP;

-- ----------------------------------------------------------------------------
-- Daily scheduled refresh -- picks up new listings/mappings automatically.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE TASK NEO4J_LINEAGE_DB.PUBLIC.REFRESH_LISTING_MAP_TASK
  WAREHOUSE = NEO4J_LINEAGE_WH
  SCHEDULE = 'USING CRON 0 7 * * * UTC'
AS
  CALL NEO4J_LINEAGE_DB.PUBLIC.REFRESH_LISTING_SEMANTIC_VIEW_MAP();

ALTER TASK NEO4J_LINEAGE_DB.PUBLIC.REFRESH_LISTING_MAP_TASK RESUME;

-- ----------------------------------------------------------------------------
-- NODES_VW -- the only change from the original is block 11
-- (DATA_PRODUCT), now live from INFORMATION_SCHEMA.LISTINGS instead of a
-- hardcoded literal. Everything else is identical to the original view.
-- ----------------------------------------------------------------------------
create or replace view NEO4J_LINEAGE_DB.PUBLIC.NODES_VW(
	NODEID,
	NODE_TYPE,
	NAME,
	DATABASE_NAME,
	SCHEMA_NAME,
	FQN,
	PARENT_SEMANTIC_VIEW,
	PARENT_LOGICAL_TABLE,
	DATA_TYPE,
	EXPRESSION,
	IS_PRIMARY_KEY,
	IS_FOREIGN_KEY,
	CONSTRAINT_NAME,
	HAS_DMF,
	DQ_ROW_COUNT,
	DQ_FRESHNESS,
	LAST_DQ_MEASUREMENT_TIME,
	DQ_NULL_COUNT,
	DQ_NULL_PERCENT,
	DQ_DUPLICATE_COUNT,
	DESCRIPTION
) as

WITH dq_latest AS (
    SELECT TABLE_NAME, METRIC_NAME, ARGUMENT_NAMES, VALUE, MEASUREMENT_TIME
    FROM SNOWFLAKE.LOCAL.DATA_QUALITY_MONITORING_RESULTS
    WHERE TABLE_DATABASE = 'TASTY_BYTES_DB' AND TABLE_SCHEMA = 'DEV'
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY TABLE_NAME, METRIC_NAME, ARGUMENT_NAMES
        ORDER BY MEASUREMENT_TIME DESC
    ) = 1
),
table_dq AS (
    SELECT TABLE_NAME,
           MAX(CASE WHEN METRIC_NAME = 'ROW_COUNT' THEN VALUE END)::BIGINT AS DQ_ROW_COUNT,
           MAX(CASE WHEN METRIC_NAME = 'FRESHNESS' THEN VALUE END)::BIGINT AS DQ_FRESHNESS,
           MAX(MEASUREMENT_TIME) AS LAST_DQ_MEASUREMENT_TIME
    FROM dq_latest
    GROUP BY TABLE_NAME
),
col_dq AS (
    SELECT TABLE_NAME,
           ARGUMENT_NAMES[0]::VARCHAR AS COLUMN_NAME,
           MAX(CASE WHEN METRIC_NAME = 'NULL_COUNT' THEN VALUE END)::BIGINT AS DQ_NULL_COUNT,
           MAX(CASE WHEN METRIC_NAME = 'DUPLICATE_COUNT' THEN VALUE END)::BIGINT AS DQ_DUPLICATE_COUNT
    FROM dq_latest
    WHERE METRIC_NAME IN ('NULL_COUNT', 'DUPLICATE_COUNT')
    GROUP BY TABLE_NAME, ARGUMENT_NAMES[0]::VARCHAR
)

-- 1. TABLE nodes — DEV (with table-level DQ)
SELECT
    ABS(HASH('TASTY_BYTES_DB.DEV.' || t.TABLE_NAME || '::TABLE'))::BIGINT AS NODEID,
    'TABLE' AS NODE_TYPE, t.TABLE_NAME AS NAME, 'TASTY_BYTES_DB' AS DATABASE_NAME, 'DEV' AS SCHEMA_NAME,
    'TASTY_BYTES_DB.DEV.' || t.TABLE_NAME AS FQN,
    NULL::VARCHAR AS PARENT_SEMANTIC_VIEW, NULL::VARCHAR AS PARENT_LOGICAL_TABLE,
    NULL::VARCHAR AS DATA_TYPE, NULL::VARCHAR AS EXPRESSION,
    NULL::BOOLEAN AS IS_PRIMARY_KEY, NULL::BOOLEAN AS IS_FOREIGN_KEY, NULL::VARCHAR AS CONSTRAINT_NAME,
    (tdq.TABLE_NAME IS NOT NULL)::BOOLEAN AS HAS_DMF,
    tdq.DQ_ROW_COUNT, tdq.DQ_FRESHNESS, tdq.LAST_DQ_MEASUREMENT_TIME,
    NULL::BIGINT AS DQ_NULL_COUNT, NULL::DOUBLE AS DQ_NULL_PERCENT, NULL::BIGINT AS DQ_DUPLICATE_COUNT,
    t.COMMENT AS DESCRIPTION
FROM TASTY_BYTES_DB.INFORMATION_SCHEMA.TABLES t
LEFT JOIN table_dq tdq ON tdq.TABLE_NAME = t.TABLE_NAME
WHERE t.TABLE_SCHEMA = 'DEV' AND t.TABLE_TYPE = 'BASE TABLE'

UNION ALL

-- 2. TABLE nodes — RAW (no DMFs)
SELECT ABS(HASH('TASTY_BYTES_DB.RAW.' || TABLE_NAME || '::TABLE'))::BIGINT,
    'TABLE', TABLE_NAME, 'TASTY_BYTES_DB', 'RAW', 'TASTY_BYTES_DB.RAW.' || TABLE_NAME,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    FALSE, NULL, NULL, NULL, NULL, NULL, NULL,
    COMMENT
FROM TASTY_BYTES_DB.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'RAW' AND TABLE_TYPE = 'BASE TABLE'

UNION ALL

-- 3. VIEW nodes — DEV (no DMFs)
SELECT ABS(HASH('TASTY_BYTES_DB.DEV.' || TABLE_NAME || '::VIEW'))::BIGINT,
    'VIEW', TABLE_NAME, 'TASTY_BYTES_DB', 'DEV', 'TASTY_BYTES_DB.DEV.' || TABLE_NAME,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    FALSE, NULL, NULL, NULL, NULL, NULL, NULL,
    COMMENT
FROM TASTY_BYTES_DB.INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA = 'DEV'

UNION ALL

-- 4. SEMANTIC_VIEW nodes
SELECT ABS(HASH('TASTY_BYTES_DB.DEV.' || NAME || '::SEMANTIC_VIEW'))::BIGINT,
    'SEMANTIC_VIEW', NAME, 'TASTY_BYTES_DB', 'DEV', 'TASTY_BYTES_DB.DEV.' || NAME,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    COMMENT
FROM TASTY_BYTES_DB.INFORMATION_SCHEMA.SEMANTIC_VIEWS
WHERE SCHEMA = 'DEV'

UNION ALL

-- 5. COLUMN nodes — DEV (PK/FK + column-level DQ)
SELECT
    ABS(HASH('TASTY_BYTES_DB.DEV.' || c.TABLE_NAME || '.' || c.COLUMN_NAME || '::COLUMN'))::BIGINT,
    'COLUMN', c.COLUMN_NAME, 'TASTY_BYTES_DB', 'DEV',
    'TASTY_BYTES_DB.DEV.' || c.TABLE_NAME || '.' || c.COLUMN_NAME,
    NULL, c.TABLE_NAME, c.DATA_TYPE, NULL,
    (pk.COLUMN_NAME IS NOT NULL)::BOOLEAN,
    (fk.FK_COLUMN_NAME IS NOT NULL)::BOOLEAN,
    COALESCE(pk.CONSTRAINT_NAME, fk.FK_NAME),
    NULL, NULL, NULL, NULL,
    cdq.DQ_NULL_COUNT,
    CASE WHEN cdq.DQ_NULL_COUNT IS NOT NULL AND tdq.DQ_ROW_COUNT > 0
         THEN ROUND((cdq.DQ_NULL_COUNT::DOUBLE / tdq.DQ_ROW_COUNT::DOUBLE) * 100, 4)
         ELSE NULL END,
    cdq.DQ_DUPLICATE_COUNT,
    c.COMMENT AS DESCRIPTION
FROM TASTY_BYTES_DB.INFORMATION_SCHEMA.COLUMNS c
LEFT JOIN NEO4J_LINEAGE_DB.PUBLIC.PK_METADATA pk
  ON pk.TABLE_NAME = c.TABLE_NAME AND pk.COLUMN_NAME = c.COLUMN_NAME AND pk.SCHEMA_NAME = 'DEV'
LEFT JOIN (SELECT DISTINCT FK_TABLE_NAME, FK_COLUMN_NAME, FK_NAME
           FROM NEO4J_LINEAGE_DB.PUBLIC.FK_METADATA WHERE FK_SCHEMA_NAME = 'DEV') fk
  ON fk.FK_TABLE_NAME = c.TABLE_NAME AND fk.FK_COLUMN_NAME = c.COLUMN_NAME
LEFT JOIN col_dq cdq ON cdq.TABLE_NAME = c.TABLE_NAME AND cdq.COLUMN_NAME = c.COLUMN_NAME
LEFT JOIN table_dq tdq ON tdq.TABLE_NAME = c.TABLE_NAME
WHERE c.TABLE_SCHEMA = 'DEV'

UNION ALL

-- 6. COLUMN nodes — RAW (no constraints, no DMFs)
SELECT ABS(HASH('TASTY_BYTES_DB.RAW.' || TABLE_NAME || '.' || COLUMN_NAME || '::COLUMN'))::BIGINT,
    'COLUMN', COLUMN_NAME, 'TASTY_BYTES_DB', 'RAW',
    'TASTY_BYTES_DB.RAW.' || TABLE_NAME || '.' || COLUMN_NAME,
    NULL, TABLE_NAME, DATA_TYPE, NULL, FALSE, FALSE, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    COMMENT
FROM TASTY_BYTES_DB.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'RAW'

UNION ALL

-- 7. LOGICAL_TABLE nodes
SELECT ABS(HASH(SEMANTIC_VIEW_NAME || '.' || NAME || '::LOGICAL_TABLE'))::BIGINT,
    'LOGICAL_TABLE', NAME, 'TASTY_BYTES_DB', 'DEV', SEMANTIC_VIEW_NAME || '.' || NAME,
    SEMANTIC_VIEW_NAME, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL
FROM TASTY_BYTES_DB.INFORMATION_SCHEMA.SEMANTIC_TABLES
WHERE SEMANTIC_VIEW_SCHEMA = 'DEV'

UNION ALL

-- 8. DIMENSION nodes
SELECT ABS(HASH(SEMANTIC_VIEW_NAME || '.' || TABLE_NAME || '.' || NAME || '::DIMENSION'))::BIGINT,
    'DIMENSION', NAME, 'TASTY_BYTES_DB', 'DEV',
    SEMANTIC_VIEW_NAME || '.' || TABLE_NAME || '.' || NAME,
    SEMANTIC_VIEW_NAME, TABLE_NAME, DATA_TYPE, EXPRESSION, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL
FROM TASTY_BYTES_DB.INFORMATION_SCHEMA.SEMANTIC_DIMENSIONS
WHERE SEMANTIC_VIEW_SCHEMA = 'DEV'

UNION ALL

-- 9. FACT nodes
SELECT ABS(HASH(SEMANTIC_VIEW_NAME || '.' || TABLE_NAME || '.' || NAME || '::FACT'))::BIGINT,
    'FACT', NAME, 'TASTY_BYTES_DB', 'DEV',
    SEMANTIC_VIEW_NAME || '.' || TABLE_NAME || '.' || NAME,
    SEMANTIC_VIEW_NAME, TABLE_NAME, DATA_TYPE, EXPRESSION, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL
FROM TASTY_BYTES_DB.INFORMATION_SCHEMA.SEMANTIC_FACTS
WHERE SEMANTIC_VIEW_SCHEMA = 'DEV'

UNION ALL

-- 10. METRIC nodes
SELECT ABS(HASH(SEMANTIC_VIEW_NAME || '.' || TABLE_NAME || '.' || NAME || '::METRIC'))::BIGINT,
    'METRIC', NAME, 'TASTY_BYTES_DB', 'DEV',
    SEMANTIC_VIEW_NAME || '.' || TABLE_NAME || '.' || NAME,
    SEMANTIC_VIEW_NAME, TABLE_NAME, DATA_TYPE, EXPRESSION, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL
FROM TASTY_BYTES_DB.INFORMATION_SCHEMA.SEMANTIC_METRICS
WHERE SEMANTIC_VIEW_SCHEMA = 'DEV'

UNION ALL

-- 11. DATA_PRODUCT nodes -- LIVE, one row per real listing visible to
-- this role, instead of a hardcoded literal.
SELECT
    ABS(HASH('DATA_PRODUCT::' || l.NAME))::BIGINT,
    'DATA_PRODUCT', COALESCE(l.TITLE, l.NAME), NULL, NULL,
    'DATA_PRODUCT::' || l.NAME,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    l.DESCRIPTION
FROM TASTY_BYTES_DB.INFORMATION_SCHEMA.LISTINGS l;

-- Quick check -- should show your real listing(s) with real titles.
SELECT NAME, FQN FROM NEO4J_LINEAGE_DB.PUBLIC.NODES_VW WHERE NODE_TYPE = 'DATA_PRODUCT';

-- Quick check -- confirms description text is coming through correctly.
SELECT NAME, NODE_TYPE, DESCRIPTION
FROM NEO4J_LINEAGE_DB.PUBLIC.NODES_VW
WHERE NODE_TYPE IN ('SEMANTIC_VIEW', 'DATA_PRODUCT')
ORDER BY NODE_TYPE;