-- ============================================================================
-- TABLE LINEAGE AUTOMATION -- complete, final, consolidated version.
-- Covers: full DEPENDS_ON lineage (Silver->Raw, and Gold->Silver, both
-- live), plus RELATIONSHIPS_VW overall (which also contains the
-- SHARED_AS block from the listing file -- run that file FIRST, since
-- this view references LISTING_SEMANTIC_VIEW_MAP, created there).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- One-time prerequisite grants (safe to re-run even if already granted).
-- IMPORTED PRIVILEGES on SNOWFLAKE is specifically what RELATIONSHIPS_VW
-- needs to read SNOWFLAKE.ACCOUNT_USAGE.OBJECT_DEPENDENCIES.
-- ----------------------------------------------------------------------------
USE ROLE ACCOUNTADMIN;
GRANT CREATE TABLE ON SCHEMA NEO4J_LINEAGE_DB.PUBLIC TO ROLE NEO4J_LINEAGE_ROLE;
GRANT CREATE TASK ON SCHEMA NEO4J_LINEAGE_DB.PUBLIC TO ROLE NEO4J_LINEAGE_ROLE;
GRANT CREATE PROCEDURE ON SCHEMA NEO4J_LINEAGE_DB.PUBLIC TO ROLE NEO4J_LINEAGE_ROLE;
GRANT CREATE VIEW ON SCHEMA NEO4J_LINEAGE_DB.PUBLIC TO ROLE NEO4J_LINEAGE_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE NEO4J_LINEAGE_ROLE;

USE ROLE NEO4J_LINEAGE_ROLE;
USE WAREHOUSE NEO4J_LINEAGE_WH;
USE DATABASE NEO4J_LINEAGE_DB;
USE SCHEMA PUBLIC;

-- ----------------------------------------------------------------------------
-- Procedure: builds the Gold->Silver lineage snapshot by looping over
-- every current Gold table and calling GET_LINEAGE dynamically.
-- GET_LINEAGE can't be called from inside a view, or with a LATERAL
-- correlated argument -- but a procedurally-built string via EXECUTE
-- IMMEDIATE works fine (confirmed via direct testing). A new Gold table
-- is picked up automatically on the next refresh, no SQL edit needed.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE NEO4J_LINEAGE_DB.PUBLIC.REFRESH_GOLD_SILVER_LINEAGE_SNAPSHOT()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    v_table_name VARCHAR;
    tables_cursor CURSOR FOR
        SELECT TABLE_NAME FROM TASTY_BYTES_DB.INFORMATION_SCHEMA.TABLES
        WHERE TABLE_SCHEMA = 'DEV' AND TABLE_TYPE = 'BASE TABLE';
BEGIN
    CREATE OR REPLACE TABLE NEO4J_LINEAGE_DB.PUBLIC.GOLD_SILVER_DEPENDS_ON_SNAPSHOT (
        SOURCE_OBJECT_DATABASE VARCHAR,
        SOURCE_OBJECT_SCHEMA VARCHAR,
        SOURCE_OBJECT_NAME VARCHAR,
        SOURCE_OBJECT_DOMAIN VARCHAR,
        TARGET_OBJECT_DATABASE VARCHAR,
        TARGET_OBJECT_SCHEMA VARCHAR,
        TARGET_OBJECT_NAME VARCHAR,
        TARGET_OBJECT_DOMAIN VARCHAR
    );

    FOR rec IN tables_cursor DO
        v_table_name := rec.TABLE_NAME;

        EXECUTE IMMEDIATE
            'SELECT * FROM TABLE(SNOWFLAKE.CORE.GET_LINEAGE(''TASTY_BYTES_DB.DEV.' ||
             v_table_name || ''', ''TABLE'', ''UPSTREAM'', 1))';

        INSERT INTO NEO4J_LINEAGE_DB.PUBLIC.GOLD_SILVER_DEPENDS_ON_SNAPSHOT
            (SOURCE_OBJECT_DATABASE, SOURCE_OBJECT_SCHEMA, SOURCE_OBJECT_NAME, SOURCE_OBJECT_DOMAIN,
             TARGET_OBJECT_DATABASE, TARGET_OBJECT_SCHEMA, TARGET_OBJECT_NAME, TARGET_OBJECT_DOMAIN)
        SELECT SOURCE_OBJECT_DATABASE, SOURCE_OBJECT_SCHEMA, SOURCE_OBJECT_NAME, SOURCE_OBJECT_DOMAIN,
               TARGET_OBJECT_DATABASE, TARGET_OBJECT_SCHEMA, TARGET_OBJECT_NAME, TARGET_OBJECT_DOMAIN
        FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
        WHERE SOURCE_OBJECT_DOMAIN = 'VIEW';
    END FOR;

    RETURN 'Refreshed Gold-Silver lineage snapshot at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;

-- Run it once now, and check the result -- expect ~10 rows, one per Gold
-- table with a real Staging source (a generated table like DIM_DATE
-- would correctly be absent).
CALL NEO4J_LINEAGE_DB.PUBLIC.REFRESH_GOLD_SILVER_LINEAGE_SNAPSHOT();
SELECT * FROM NEO4J_LINEAGE_DB.PUBLIC.GOLD_SILVER_DEPENDS_ON_SNAPSHOT ORDER BY TARGET_OBJECT_NAME;

-- ----------------------------------------------------------------------------
-- Daily scheduled refresh -- picks up new Gold tables and any lineage
-- changes automatically.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE TASK NEO4J_LINEAGE_DB.PUBLIC.REFRESH_GOLD_SILVER_LINEAGE_TASK
  WAREHOUSE = NEO4J_LINEAGE_WH
  SCHEDULE = 'USING CRON 0 7 * * * UTC'
AS
  CALL NEO4J_LINEAGE_DB.PUBLIC.REFRESH_GOLD_SILVER_LINEAGE_SNAPSHOT();

ALTER TASK NEO4J_LINEAGE_DB.PUBLIC.REFRESH_GOLD_SILVER_LINEAGE_TASK RESUME;

-- ----------------------------------------------------------------------------
-- RELATIONSHIPS_VW -- the complete, final version. Two blocks changed
-- from the very original: 1b (Gold->Silver, now reading the snapshot
-- table above instead of nothing) and 5a (SHARED_AS, now reading the
-- listing mapping table from the OTHER file instead of two hardcoded
-- literals). Every other block is untouched.
-- ----------------------------------------------------------------------------
create or replace view NEO4J_LINEAGE_DB.PUBLIC.RELATIONSHIPS_VW(
	SOURCENODEID,
	TARGETNODEID,
	RELATIONSHIP_TYPE,
	SOURCE_NAME,
	TARGET_NAME,
	DETAIL
) as

-- 1. DEPENDS_ON (Silver -> Raw)
SELECT
    ABS(HASH(d.REFERENCING_DATABASE || '.' || d.REFERENCING_SCHEMA || '.' || d.REFERENCING_OBJECT_NAME || '::'
             || CASE d.REFERENCING_OBJECT_DOMAIN WHEN 'TABLE' THEN 'TABLE' WHEN 'VIEW' THEN 'VIEW' ELSE UPPER(d.REFERENCING_OBJECT_DOMAIN) END))::BIGINT AS SOURCENODEID,
    ABS(HASH(d.REFERENCED_DATABASE || '.' || d.REFERENCED_SCHEMA || '.' || d.REFERENCED_OBJECT_NAME || '::'
             || CASE d.REFERENCED_OBJECT_DOMAIN WHEN 'TABLE' THEN 'TABLE' WHEN 'VIEW' THEN 'VIEW' ELSE UPPER(d.REFERENCED_OBJECT_DOMAIN) END))::BIGINT AS TARGETNODEID,
    'DEPENDS_ON' AS RELATIONSHIP_TYPE, d.REFERENCING_OBJECT_NAME AS SOURCE_NAME, d.REFERENCED_OBJECT_NAME AS TARGET_NAME, d.DEPENDENCY_TYPE AS DETAIL
FROM SNOWFLAKE.ACCOUNT_USAGE.OBJECT_DEPENDENCIES d
WHERE d.REFERENCING_DATABASE = 'TASTY_BYTES_DB' AND d.REFERENCING_SCHEMA = 'DEV'

UNION ALL

-- 1b. DEPENDS_ON (Gold -> Silver, via scheduled GET_LINEAGE snapshot)
SELECT
    ABS(HASH(s.TARGET_OBJECT_DATABASE || '.' || s.TARGET_OBJECT_SCHEMA || '.' || s.TARGET_OBJECT_NAME || '::'
             || CASE s.TARGET_OBJECT_DOMAIN WHEN 'TABLE' THEN 'TABLE' WHEN 'VIEW' THEN 'VIEW' ELSE UPPER(s.TARGET_OBJECT_DOMAIN) END))::BIGINT AS SOURCENODEID,
    ABS(HASH(s.SOURCE_OBJECT_DATABASE || '.' || s.SOURCE_OBJECT_SCHEMA || '.' || s.SOURCE_OBJECT_NAME || '::'
             || CASE s.SOURCE_OBJECT_DOMAIN WHEN 'TABLE' THEN 'TABLE' WHEN 'VIEW' THEN 'VIEW' ELSE UPPER(s.SOURCE_OBJECT_DOMAIN) END))::BIGINT AS TARGETNODEID,
    'DEPENDS_ON' AS RELATIONSHIP_TYPE,
    s.TARGET_OBJECT_NAME AS SOURCE_NAME,
    s.SOURCE_OBJECT_NAME AS TARGET_NAME,
    'via GET_LINEAGE snapshot' AS DETAIL
FROM NEO4J_LINEAGE_DB.PUBLIC.GOLD_SILVER_DEPENDS_ON_SNAPSHOT s

UNION ALL

-- 2. HAS_COLUMN — DEV
SELECT
    ABS(HASH('TASTY_BYTES_DB.DEV.' || c.TABLE_NAME || '::' || CASE WHEN t.TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE 'VIEW' END))::BIGINT,
    ABS(HASH('TASTY_BYTES_DB.DEV.' || c.TABLE_NAME || '.' || c.COLUMN_NAME || '::COLUMN'))::BIGINT,
    'HAS_COLUMN', c.TABLE_NAME, c.COLUMN_NAME, c.DATA_TYPE
FROM TASTY_BYTES_DB.INFORMATION_SCHEMA.COLUMNS c
JOIN TASTY_BYTES_DB.INFORMATION_SCHEMA.TABLES t ON t.TABLE_SCHEMA = c.TABLE_SCHEMA AND t.TABLE_NAME = c.TABLE_NAME
WHERE c.TABLE_SCHEMA = 'DEV'

UNION ALL

-- 3. HAS_COLUMN — RAW
SELECT
    ABS(HASH('TASTY_BYTES_DB.RAW.' || c.TABLE_NAME || '::TABLE'))::BIGINT,
    ABS(HASH('TASTY_BYTES_DB.RAW.' || c.TABLE_NAME || '.' || c.COLUMN_NAME || '::COLUMN'))::BIGINT,
    'HAS_COLUMN', c.TABLE_NAME, c.COLUMN_NAME, c.DATA_TYPE
FROM TASTY_BYTES_DB.INFORMATION_SCHEMA.COLUMNS c
WHERE c.TABLE_SCHEMA = 'RAW'

UNION ALL

-- 4. DEFINED_OVER
SELECT
    ABS(HASH('TASTY_BYTES_DB.DEV.' || st.SEMANTIC_VIEW_NAME || '::SEMANTIC_VIEW'))::BIGINT,
    ABS(HASH(st.BASE_TABLE_CATALOG || '.' || st.BASE_TABLE_SCHEMA || '.' || st.BASE_TABLE_NAME || '::TABLE'))::BIGINT,
    'DEFINED_OVER', st.SEMANTIC_VIEW_NAME, st.BASE_TABLE_NAME, NULL
FROM TASTY_BYTES_DB.INFORMATION_SCHEMA.SEMANTIC_TABLES st
WHERE st.SEMANTIC_VIEW_SCHEMA = 'DEV'

UNION ALL

-- 5a. SHARED_AS -- live, from the listing mapping table (created and
-- refreshed in the OTHER file -- this is the one cross-reference between
-- the two files). Add a row to LISTING_SEMANTIC_VIEW_MAP (or let its own
-- daily refresh pick it up) any time a new semantic view should be
-- linked to a listing -- no view SQL changes needed ever again.
SELECT
    ABS(HASH('TASTY_BYTES_DB.DEV.' || m.SEMANTIC_VIEW_NAME || '::SEMANTIC_VIEW'))::BIGINT,
    ABS(HASH('DATA_PRODUCT::' || m.LISTING_NAME))::BIGINT,
    'SHARED_AS', m.SEMANTIC_VIEW_NAME, m.LISTING_NAME, NULL
FROM NEO4J_LINEAGE_DB.PUBLIC.LISTING_SEMANTIC_VIEW_MAP m

UNION ALL

-- 6. BELONGS_TO_LOGICAL_TABLE (dimensions)
SELECT ABS(HASH(sd.SEMANTIC_VIEW_NAME || '.' || sd.TABLE_NAME || '.' || sd.NAME || '::DIMENSION'))::BIGINT,
    ABS(HASH(sd.SEMANTIC_VIEW_NAME || '.' || sd.TABLE_NAME || '::LOGICAL_TABLE'))::BIGINT,
    'BELONGS_TO_LOGICAL_TABLE', sd.NAME, sd.TABLE_NAME, 'DIMENSION'
FROM TASTY_BYTES_DB.INFORMATION_SCHEMA.SEMANTIC_DIMENSIONS sd WHERE sd.SEMANTIC_VIEW_SCHEMA = 'DEV'

UNION ALL

-- 7. BELONGS_TO_LOGICAL_TABLE (facts)
SELECT ABS(HASH(sf.SEMANTIC_VIEW_NAME || '.' || sf.TABLE_NAME || '.' || sf.NAME || '::FACT'))::BIGINT,
    ABS(HASH(sf.SEMANTIC_VIEW_NAME || '.' || sf.TABLE_NAME || '::LOGICAL_TABLE'))::BIGINT,
    'BELONGS_TO_LOGICAL_TABLE', sf.NAME, sf.TABLE_NAME, 'FACT'
FROM TASTY_BYTES_DB.INFORMATION_SCHEMA.SEMANTIC_FACTS sf WHERE sf.SEMANTIC_VIEW_SCHEMA = 'DEV'

UNION ALL

-- 8. BELONGS_TO_LOGICAL_TABLE (metrics)
SELECT ABS(HASH(sm.SEMANTIC_VIEW_NAME || '.' || sm.TABLE_NAME || '.' || sm.NAME || '::METRIC'))::BIGINT,
    ABS(HASH(sm.SEMANTIC_VIEW_NAME || '.' || sm.TABLE_NAME || '::LOGICAL_TABLE'))::BIGINT,
    'BELONGS_TO_LOGICAL_TABLE', sm.NAME, sm.TABLE_NAME, 'METRIC'
FROM TASTY_BYTES_DB.INFORMATION_SCHEMA.SEMANTIC_METRICS sm WHERE sm.SEMANTIC_VIEW_SCHEMA = 'DEV'

UNION ALL

-- 9. HAS_DIMENSION
SELECT ABS(HASH(sd.SEMANTIC_VIEW_NAME || '.' || sd.TABLE_NAME || '::LOGICAL_TABLE'))::BIGINT,
    ABS(HASH(sd.SEMANTIC_VIEW_NAME || '.' || sd.TABLE_NAME || '.' || sd.NAME || '::DIMENSION'))::BIGINT,
    'HAS_DIMENSION', sd.TABLE_NAME, sd.NAME, sd.DATA_TYPE
FROM TASTY_BYTES_DB.INFORMATION_SCHEMA.SEMANTIC_DIMENSIONS sd WHERE sd.SEMANTIC_VIEW_SCHEMA = 'DEV'

UNION ALL

-- 10. HAS_FACT
SELECT ABS(HASH(sf.SEMANTIC_VIEW_NAME || '.' || sf.TABLE_NAME || '::LOGICAL_TABLE'))::BIGINT,
    ABS(HASH(sf.SEMANTIC_VIEW_NAME || '.' || sf.TABLE_NAME || '.' || sf.NAME || '::FACT'))::BIGINT,
    'HAS_FACT', sf.TABLE_NAME, sf.NAME, sf.DATA_TYPE
FROM TASTY_BYTES_DB.INFORMATION_SCHEMA.SEMANTIC_FACTS sf WHERE sf.SEMANTIC_VIEW_SCHEMA = 'DEV'

UNION ALL

-- 11. HAS_METRIC
SELECT ABS(HASH(sm.SEMANTIC_VIEW_NAME || '.' || sm.TABLE_NAME || '::LOGICAL_TABLE'))::BIGINT,
    ABS(HASH(sm.SEMANTIC_VIEW_NAME || '.' || sm.TABLE_NAME || '.' || sm.NAME || '::METRIC'))::BIGINT,
    'HAS_METRIC', sm.TABLE_NAME, sm.NAME, sm.DATA_TYPE
FROM TASTY_BYTES_DB.INFORMATION_SCHEMA.SEMANTIC_METRICS sm WHERE sm.SEMANTIC_VIEW_SCHEMA = 'DEV'

UNION ALL

-- 12. REFERENCES (semantic relationships)
SELECT ABS(HASH(sr.SEMANTIC_VIEW_NAME || '.' || sr.TABLE_NAME || '::LOGICAL_TABLE'))::BIGINT,
    ABS(HASH(sr.SEMANTIC_VIEW_NAME || '.' || sr.REF_TABLE_NAME || '::LOGICAL_TABLE'))::BIGINT,
    'REFERENCES', sr.TABLE_NAME, sr.REF_TABLE_NAME, sr.NAME
FROM TASTY_BYTES_DB.INFORMATION_SCHEMA.SEMANTIC_RELATIONSHIPS sr WHERE sr.SEMANTIC_VIEW_SCHEMA = 'DEV'

UNION ALL

-- 13. FK_TO
SELECT
    ABS(HASH('TASTY_BYTES_DB.DEV.' || fk.FK_TABLE_NAME || '.' || fk.FK_COLUMN_NAME || '::COLUMN'))::BIGINT,
    ABS(HASH('TASTY_BYTES_DB.DEV.' || fk.PK_TABLE_NAME || '.' || fk.PK_COLUMN_NAME || '::COLUMN'))::BIGINT,
    'FK_TO',
    fk.FK_TABLE_NAME || '.' || fk.FK_COLUMN_NAME,
    fk.PK_TABLE_NAME || '.' || fk.PK_COLUMN_NAME,
    fk.FK_NAME
FROM NEO4J_LINEAGE_DB.PUBLIC.FK_METADATA fk
WHERE fk.FK_SCHEMA_NAME = 'DEV';

-- ----------------------------------------------------------------------------
-- VERIFICATION
-- ----------------------------------------------------------------------------
SELECT
    sn.NODE_TYPE AS source_type,
    tn.NODE_TYPE AS target_type,
    COUNT(*)     AS edge_count
FROM NEO4J_LINEAGE_DB.PUBLIC.RELATIONSHIPS_VW r
JOIN NEO4J_LINEAGE_DB.PUBLIC.NODES_VW sn ON sn.NODEID = r.SOURCENODEID
JOIN NEO4J_LINEAGE_DB.PUBLIC.NODES_VW tn ON tn.NODEID = r.TARGETNODEID
WHERE r.RELATIONSHIP_TYPE = 'DEPENDS_ON'
GROUP BY sn.NODE_TYPE, tn.NODE_TYPE
ORDER BY source_type, target_type;
-- Expect: VIEW->TABLE (7, Silver->Raw) and TABLE->VIEW (~10, Gold->Silver)

SELECT SOURCE_NAME, TARGET_NAME FROM NEO4J_LINEAGE_DB.PUBLIC.RELATIONSHIPS_VW
WHERE RELATIONSHIP_TYPE = 'SHARED_AS';
-- Expect: one row per semantic view that's actually part of a real listing