USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS PBI_TASTY_BYTES_ROLE;

GRANT USAGE
ON WAREHOUSE TASTY_BYTES_WH
TO ROLE PBI_TASTY_BYTES_ROLE;

GRANT USAGE
ON DATABASE TASTY_BYTES_DB
TO ROLE PBI_TASTY_BYTES_ROLE;

GRANT USAGE
ON SCHEMA TASTY_BYTES_DB.DEV
TO ROLE PBI_TASTY_BYTES_ROLE;

GRANT SELECT
ON ALL TABLES IN SCHEMA TASTY_BYTES_DB.DEV
TO ROLE PBI_TASTY_BYTES_ROLE;

GRANT SELECT
ON FUTURE TABLES IN SCHEMA TASTY_BYTES_DB.DEV
TO ROLE PBI_TASTY_BYTES_ROLE;

GRANT CREATE SEMANTIC VIEW
ON SCHEMA TASTY_BYTES_DB.DEV
TO ROLE PBI_TASTY_BYTES_ROLE;

GRANT CREATE STAGE
ON SCHEMA TASTY_BYTES_DB.DEV
TO ROLE PBI_TASTY_BYTES_ROLE;

GRANT ROLE PBI_TASTY_BYTES_ROLE
TO USER SAHJAD;